title: Passive Voice Coach
emoji: 🐠
colorFrom: green
colorTo: blue
sdk: gradio
sdk_version: 5.12.0
app_file: app.py
pinned: false
license: mit
short_description: Converts passive voice sentences to active voice.
